missing lsblk warning

diff --git a/amount b/amount
--- a/amount
+++ b/amount
@@ -75,6 +75,8 @@ if [ -e "$HOME/.amount_map" ]; then
             fi
         }
         MOUNTNAME=$(map-uuid-to-mount "$UUID")
+    else
+        echo "$BOLD$YELLOW*$RESET ${BOLD}Warning:$RESET `lsblk' not found, custom mount point disabled" 1>&2
     fi
 fi
 
